# Generated by Django 2.2.2 on 2019-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='weather',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
